#-----------------------------#
# Server port settings        #
#-----------------------------#
server.port=8080

#-----------------------------#
# Spring application settings #
#-----------------------------#
spring.application.name=sm-static-hub-springboot-webapp

#------------------------------#
#        Context Path          #
#------------------------------#
server.servlet.context-path=/sm-static-hub

#----------------------------------------------#
#        Enable Logging Shutdown Hook          #
#----------------------------------------------#
logging.shutdown-hook.enabled=true
