USE stock_market_dev;

DELETE FROM QUARTZ_SIMPLE_TRIGGERS WHERE TRIGGER_NAME LIKE 'TEST%';
DELETE FROM QUARTZ_BLOB_TRIGGERS WHERE TRIGGER_NAME LIKE 'TEST%';
DELETE FROM QUARTZ_CRON_TRIGGERS WHERE TRIGGER_NAME LIKE 'TEST%';
DELETE FROM QUARTZ_SIMPROP_TRIGGERS WHERE TRIGGER_NAME LIKE 'TEST%';
DELETE FROM QUARTZ_TRIGGERS WHERE JOB_NAME LIKE 'TEST%';
DELETE FROM QUARTZ_JOB_DETAILS WHERE JOB_NAME LIKE 'TEST%';

COMMIT;