package rave.code.entity.quartz.enums;

public enum NSEStockClassification {

    EMPTY("Index", "Index"),

    E1("E1","E1(Partly paid-up equity shares)"),
    EQ("EQ", "Equity"),

    BE("BE","Book Entry(Trade-to-Trade (T2T) segment)"),
    BL("BL","Book Entry(Trade-to-Trade (T2T) segment)"),
    BT("BT","Book Entry(Trade-to-Trade (T2T) segment)"),
    BZ("BZ","Blacklisted"),

    D0("D0","Fully convertible debentures"),
    D1("D1","Fully convertible debentures"),
    D2("D2","Fully convertible debentures"),
    D3("D3","Fully convertible debentures"),
    D4("D4","Fully convertible debentures"),
    D5("D5","Fully convertible debentures"),
    D6("D6","Fully convertible debentures"),
    D7("D7","Fully convertible debentures"),
    D8("D8","Fully convertible debentures"),
    D9("D9","Fully convertible debentures"),

    DA("DA","Fully convertible debentures"),
    DB("DB","Fully convertible debentures"),
    DC("DC","Fully convertible debentures"),
    DD("DD","Fully convertible debentures"),
    DE("DE","Fully convertible debentures"),
    DF("DF","Fully convertible debentures"),
    DG("DG","Fully convertible debentures"),
    DH("DH","Fully convertible debentures"),
    DI("DI","Fully convertible debentures"),
    DJ("DJ","Fully convertible debentures"),
    DK("DK","Fully convertible debentures"),
    DL("DL","Fully convertible debentures"),
    DM("DM","Fully convertible debentures"),
    DN("DN","Fully convertible debentures"),
    DO("DO","Fully convertible debentures"),
    DP("DP","Fully convertible debentures"),
    DQ("DQ","Fully convertible debentures"),
    DR("DR","Fully convertible debentures"),
    DS("DS","Fully convertible debentures"),
    DT("DT","Fully convertible debentures"),
    DU("DU","Fully convertible debentures"),
    DV("DV","Fully convertible debentures"),
    DW("DW","Fully convertible debentures"),
    DX("DX","Fully convertible debentures"),
    DY("DY","Fully convertible debentures"),
    DZ("DZ","Fully convertible debentures"),

    F0("F0","Convertible preference shares"),
    F1("F1","Convertible preference shares"),
    F2("F2","Convertible preference shares"),
    F3("F3","Convertible preference shares"),
    F4("F4","Convertible preference shares"),
    F5("F5","Convertible preference shares"),
    F6("F6","Convertible preference shares"),
    F7("F7","Convertible preference shares"),
    F8("F8","Convertible preference shares"),
    F9("F9","Convertible preference shares"),

    FA("FA","Convertible preference shares"),
    FB("FB","Convertible preference shares"),
    FC("FC","Convertible preference shares"),
    FD("FD","Convertible preference shares"),
    FE("FE","Convertible preference shares"),
    FF("FF","Convertible preference shares"),
    FG("FG","Convertible preference shares"),
    FH("FH","Convertible preference shares"),
    FI("FI","Convertible preference shares"),
    FJ("FJ","Convertible preference shares"),
    FK("FK","Convertible preference shares"),
    FL("FL","Convertible preference shares"),
    FM("FM","Convertible preference shares"),
    FN("FN","Convertible preference shares"),
    FO("FO","Convertible preference shares"),
    FP("FP","Convertible preference shares"),
    FQ("FQ","Convertible preference shares"),
    FR("FR","Convertible preference shares"),
    FS("FS","Convertible preference shares"),
    FT("FT","Convertible preference shares"),
    FU("FU","Convertible preference shares"),
    FV("FV","Convertible preference shares"),
    FW("FW","Convertible preference shares"),
    FX("FX","Convertible preference shares"),
    FY("FY","Convertible preference shares"),
    FZ("FZ","Convertible preference shares"),

    GB("GB","Gold Bonds (Sovereign Gold Bonds)"),
    GS("GS","Government Securities (State Development Loans, etc.)"),

    IV("IV","Implied Volatile"),

    N0("N0","Non-convertible debentures (Fixed income instruments)"),
    N1("N1","Non-convertible debentures (Fixed income instruments)"),
    N2("N2","Non-convertible debentures (Fixed income instruments)"),
    N3("N3","Non-convertible debentures (Fixed income instruments)"),
    N4("N4","Non-convertible debentures (Fixed income instruments)"),
    N5("N5","Non-convertible debentures (Fixed income instruments)"),
    N6("N6","Non-convertible debentures (Fixed income instruments)"),
    N7("N7","Non-convertible debentures (Fixed income instruments)"),
    N8("N8","Non-convertible debentures (Fixed income instruments)"),
    N9("N9","Non-convertible debentures (Fixed income instruments)"),

    NA("NA","Non-convertible debentures (Fixed income instruments)"),
    NB("NB","Non-convertible debentures (Fixed income instruments)"),
    NC("NC","Non-convertible debentures (Fixed income instruments)"),
    ND("ND","Non-convertible debentures (Fixed income instruments)"),
    NE("NE","Non-convertible debentures (Fixed income instruments)"),
    NF("NF","Non-convertible debentures (Fixed income instruments)"),
    NG("NG","Non-convertible debentures (Fixed income instruments)"),
    NH("NH","Non-convertible debentures (Fixed income instruments)"),
    NI("NI","Non-convertible debentures (Fixed income instruments)"),
    NJ("NJ","Non-convertible debentures (Fixed income instruments)"),
    NK("NK","Non-convertible debentures (Fixed income instruments)"),
    NL("NL","Non-convertible debentures (Fixed income instruments)"),
    NM("NM","Non-convertible debentures (Fixed income instruments)"),
    NN("NN","Non-convertible debentures (Fixed income instruments)"),
    NO("NO","Non-convertible debentures (Fixed income instruments)"),
    NP("NP","Non-convertible debentures (Fixed income instruments)"),
    NQ("NQ","Non-convertible debentures (Fixed income instruments)"),
    NR("NR","Non-convertible debentures (Fixed income instruments)"),
    NS("NS","Non-convertible debentures (Fixed income instruments)"),
    NT("NT","Non-convertible debentures (Fixed income instruments)"),
    NU("NU","Non-convertible debentures (Fixed income instruments)"),
    NV("NV","Non-convertible debentures (Fixed income instruments)"),
    NW("NW","Non-convertible debentures (Fixed income instruments)"),
    NX("NX","Non-convertible debentures (Fixed income instruments)"),
    NY("NY","Non-convertible debentures (Fixed income instruments)"),
    NZ("NZ","Non-convertible debentures (Fixed income instruments)"),

    P1("P1","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    P2("P2","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    P3("P3","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    P4("P4","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    P5("P5","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    P6("P6","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    P7("P7","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    P8("P8","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    P9("P8","Non-Convertible Preference Shares(Cannot be converted into equity)"),

    PA("PA","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PB("PB","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PC("PC","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PD("PD","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PE("PE","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PF("PF","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PG("PG","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PH("PH","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PI("PI","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PJ("PJ","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PK("PK","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PL("PL","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PM("PM","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PN("PN","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PO("PO","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PP("PP","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PQ("PQ","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PR("PR","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PS("PS","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PT("PT","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PU("PU","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PV("PV","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PW("PW","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PX("PX","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PY("PY","Non-Convertible Preference Shares(Cannot be converted into equity)"),
    PZ("PZ","Non-Convertible Preference Shares(Cannot be converted into equity)"),

    Q0("Q0","Convertible preference shares"),
    Q1("Q1","Convertible preference shares"),
    Q2("Q2","Convertible preference shares"),
    Q3("Q3","Convertible preference shares"),
    Q4("Q4","Convertible preference shares"),
    Q5("Q5","Convertible preference shares"),
    Q6("Q6","Convertible preference shares"),
    Q7("Q7","Convertible preference shares"),
    Q8("Q8","Convertible preference shares"),
    Q9("Q9","Convertible preference shares"),

    QA("QA","Convertible preference shares"),
    QB("QB","Convertible preference shares"),
    QC("QC","Convertible preference shares"),
    QD("QD","Convertible preference shares"),
    QE("QE","Convertible preference shares"),
    QF("QF","Convertible preference shares"),
    QG("QG","Convertible preference shares"),
    QH("QH","Convertible preference shares"),
    QI("QI","Convertible preference shares"),
    QJ("QJ","Convertible preference shares"),
    QK("QK","Convertible preference shares"),
    QL("QL","Convertible preference shares"),
    QM("QM","Convertible preference shares"),
    QN("QN","Convertible preference shares"),
    QO("QO","Convertible preference shares"),
    QP("QP","Convertible preference shares"),
    QQ("QQ","Convertible preference shares"),
    QR("QR","Convertible preference shares"),
    QS("QS","Convertible preference shares"),
    QT("QT","Convertible preference shares"),
    QU("QU","Convertible preference shares"),
    QV("QV","Convertible preference shares"),
    QW("QW","Convertible preference shares"),
    QX("QX","Convertible preference shares"),
    QY("QY","Convertible preference shares"),
    QZ("QZ","Convertible preference shares"),

    RR("RR","RR Equity Series"),

    S0("S0","Fully convertible debentures"),
    S1("S1","Fully convertible debentures"),
    S2("S2","Fully convertible debentures"),
    S3("S3","Fully convertible debentures"),
    S4("S4","Fully convertible debentures"),
    S5("S5","Fully convertible debentures"),
    S6("S6","Fully convertible debentures"),
    S7("S7","Fully convertible debentures"),
    S8("S8","Fully convertible debentures"),
    S9("S9","Fully convertible debentures"),

    SA("SA","Fully convertible debentures"),
    SB("SB","Fully convertible debentures"),
    SC("SC","Fully convertible debentures"),
    SD("SD","Fully convertible debentures"),
    SE("SE","Fully convertible debentures"),
    SF("SF","Fully convertible debentures"),
    SG("SG","State Development Loan(Government debt instrument)"),
    SH("SH","Fully convertible debentures"),
    SI("SI","Fully convertible debentures"),
    SJ("SJ","Fully convertible debentures"),
    SK("SK","Fully convertible debentures"),
    SL("SL","Fully convertible debentures"),
    SM("SM","Small and Medium sized Enterprise"),
    SN("SN","Fully convertible debentures"),
    SO("SO","Fully convertible debentures"),
    SP("SP","Fully convertible debentures"),
    SQ("SQ","Fully convertible debentures"),
    SR("SR","Fully convertible debentures"),
    SS("SS","Fully convertible debentures"),
    ST("ST","shares traded on the SME and requires compulsory delivery"),
    SU("SU","Fully convertible debentures"),
    SV("SV","Fully convertible debentures"),
    SW("SW","Fully convertible debentures"),
    SX("SX","Fully convertible debentures"),
    SY("SY","Fully convertible debentures"),
    SZ("SZ","Fully convertible debentures"),


    T0("T0","T+0(Settled on the same day)"),
    TB("TB","Treasury Bills (short-term govt securities)"),

    X1("X1","Blacklisted"),

    Y0("Y0","Non-convertible debentures (Cannot be converted into equity)"),
    Y1("Y1","Non-convertible debentures (Cannot be converted into equity)"),
    Y2("Y2","Non-convertible debentures (Cannot be converted into equity)"),
    Y3("Y3","Non-convertible debentures (Cannot be converted into equity)"),
    Y4("Y4","Non-convertible debentures (Cannot be converted into equity)"),
    Y5("Y5","Non-convertible debentures (Cannot be converted into equity)"),
    Y6("Y6","Non-convertible debentures (Cannot be converted into equity)"),
    Y7("Y7","Non-convertible debentures (Cannot be converted into equity)"),
    Y8("Y8","Non-convertible debentures (Cannot be converted into equity)"),
    Y9("Y9","Non-convertible debentures (Cannot be converted into equity)"),

    YA("YA","Non-convertible debentures (Cannot be converted into equity)"),
    YB("YB","Non-convertible debentures (Cannot be converted into equity)"),
    YC("YC","Non-convertible debentures (Cannot be converted into equity)"),
    YD("YD","Non-convertible debentures (Cannot be converted into equity)"),
    YE("YE","Non-convertible debentures (Cannot be converted into equity)"),
    YF("YF","Non-convertible debentures (Cannot be converted into equity)"),
    YG("YG","Non-convertible debentures (Cannot be converted into equity)"),
    YH("YH","Non-convertible debentures (Cannot be converted into equity)"),
    YI("YI","Non-convertible debentures (Cannot be converted into equity)"),
    YJ("YJ","Non-convertible debentures (Cannot be converted into equity)"),
    YK("YK","Non-convertible debentures (Cannot be converted into equity)"),
    YL("YL","Non-convertible debentures (Cannot be converted into equity)"),
    YM("YM","Non-convertible debentures (Cannot be converted into equity)"),
    YN("YN","Non-convertible debentures (Cannot be converted into equity)"),
    YO("YO","Non-convertible debentures (Cannot be converted into equity)"),
    YP("YP","Non-convertible debentures (Cannot be converted into equity)"),
    YQ("YQ","Non-convertible debentures (Cannot be converted into equity)"),
    YR("YR","Non-convertible debentures (Cannot be converted into equity)"),
    YS("YS","Non-convertible debentures (Cannot be converted into equity)"),
    YT("YT","Non-convertible debentures (Cannot be converted into equity)"),
    YU("YU","Non-convertible debentures (Cannot be converted into equity)"),
    YV("YV","Non-convertible debentures (Cannot be converted into equity)"),
    YW("YW","Non-convertible debentures (Cannot be converted into equity)"),
    YX("YX","Non-convertible debentures (Cannot be converted into equity)"),
    YY("YY","Non-convertible debentures (Cannot be converted into equity)"),
    YZ("YZ","Non-convertible debentures (Cannot be converted into equity)"),

    Z0("Z0","Non-convertible debentures (Cannot be converted into equity)"),
    Z1("Z1","Non-convertible debentures (Cannot be converted into equity)"),
    Z2("Z2","Non-convertible debentures (Cannot be converted into equity)"),
    Z3("Z3","Non-convertible debentures (Cannot be converted into equity)"),
    Z4("Z4","Non-convertible debentures (Cannot be converted into equity)"),
    Z5("Z5","Non-convertible debentures (Cannot be converted into equity)"),
    Z6("Z6","Non-convertible debentures (Cannot be converted into equity)"),
    Z7("Z7","Non-convertible debentures (Cannot be converted into equity)"),
    Z8("Z8","Non-convertible debentures (Cannot be converted into equity)"),
    Z9("Z9","Non-convertible debentures (Cannot be converted into equity)"),

    ZA("ZA","Non-convertible debentures (Cannot be converted into equity)"),
    ZB("ZB","Non-convertible debentures (Cannot be converted into equity)"),
    ZC("ZC","Non-convertible debentures (Cannot be converted into equity)"),
    ZD("ZD","Non-convertible debentures (Cannot be converted into equity)"),
    ZE("ZE","Non-convertible debentures (Cannot be converted into equity)"),
    ZF("ZF","Non-convertible debentures (Cannot be converted into equity)"),
    ZG("ZG","Non-convertible debentures (Cannot be converted into equity)"),
    ZH("ZH","Non-convertible debentures (Cannot be converted into equity)"),
    ZI("ZI","Non-convertible debentures (Cannot be converted into equity)"),
    ZJ("ZJ","Non-convertible debentures (Cannot be converted into equity)"),
    ZK("ZK","Non-convertible debentures (Cannot be converted into equity)"),
    ZL("ZL","Non-convertible debentures (Cannot be converted into equity)"),
    ZM("ZM","Non-convertible debentures (Cannot be converted into equity)"),
    ZN("ZN","Non-convertible debentures (Cannot be converted into equity)"),
    ZO("ZO","Non-convertible debentures (Cannot be converted into equity)"),
    ZP("ZP","Non-convertible debentures (Cannot be converted into equity)"),
    ZQ("ZQ","Non-convertible debentures (Cannot be converted into equity)"),
    ZR("ZR","Non-convertible debentures (Cannot be converted into equity)"),
    ZS("ZS","Non-convertible debentures (Cannot be converted into equity)"),
    ZT("ZT","Non-convertible debentures (Cannot be converted into equity)"),
    ZU("ZU","Non-convertible debentures (Cannot be converted into equity)"),
    ZV("ZV","Non-convertible debentures (Cannot be converted into equity)"),
    ZW("ZW","Non-convertible debentures (Cannot be converted into equity)"),
    ZX("ZX","Non-convertible debentures (Cannot be converted into equity)"),
    ZY("ZY","Non-convertible debentures (Cannot be converted into equity)"),
    ZZ("ZZ","Non-convertible debentures (Cannot be converted into equity)"),

    DEFAULT("NEW","New Series by NSE");

    private String seriesCode;
    private String description;

    private NSEStockClassification(String seriesCode, String description) {
        this.seriesCode = seriesCode;
        this.description = description;
    }

    public String getSeriesCode(){
        return this.seriesCode;
    }

    public String getDescription(){
        return this.description;
    }

    public static final NSEStockClassification getClassification(String seriesCode){
        NSEStockClassification[] nseStockClassifications = NSEStockClassification.values();
        for (NSEStockClassification nseStockClassification: nseStockClassifications) {
            if(seriesCode.equals(nseStockClassification.getSeriesCode())){
                return nseStockClassification;
            }
        }
        return NSEStockClassification.DEFAULT;
    }
}
