package rave.code.quartz.enums;

public enum CronExpression {

    NOW("* * * ? * SUN-SAT"),
    EVERY_3RD_MINUTE_OF_THE_CLOCK_ON_ALL_DAYS("* */3 * * * ?"),
    EVERY_5TH_MINUTE_OF_THE_CLOCK_ON_ALL_DAYS("* */5 * * * ?"),
    EVERY_3RD_MINUTE_OF_THE_CLOCK_FROM_MONDAY_TO_FRIDAY("* */3 * ? * MON-FRI"),
    EVERY_5TH_MINUTE_OF_THE_CLOCK_FROM_MONDAY_TO_FRIDAY("* */5 * ? * MON-FRI"),
    EVERY_3RD_MINUTE_OF_THE_CLOCK_FROM_MONDAY_TO_FRIDAY_BETWEEN_9_15AM_TO_10AM("* 15-59/3 9-10 ? * MON-FRI"),
    EVERY_3RD_MINUTE_OF_THE_CLOCK_FROM_MONDAY_TO_FRIDAY_BETWEEN_10AM_TO_4PM("* */3 10-16 ? * MON-FRI"),
    EVERY_5TH_MINUTE_OF_THE_CLOCK_FROM_MONDAY_TO_FRIDAY_BETWEEN_9_15AM_TO_10AM("* 15-59/5 9-10 ? * MON-FRI"),
    EVERY_5TH_MINUTE_OF_THE_CLOCK_FROM_MONDAY_TO_FRIDAY_BETWEEN_10AM_TO_4PM("* */5 10-16 ? * MON-FRI"),
    AT_8AM_MONDAY_TO_FRIDAY("0 0 8 ? * MON-FRI"),
    AT_4PM_MONDAY_TO_FRIDAY("0 0 16 ? * MON-FRI"),
    
    /******************* NSE Cron Expressions *******************/
    NSE_BLOCK_DEAL_FIRST_SESSION_AT_08_59_59_AM_MONDAY_TO_FRIDAY("59 59 8 ? * MON-FRI"),
    NSE_BLOCK_DEAL_SECOND_SESSION_BETWEEN_AT_02_19_59_PM_MONDAY_TO_FRIDAY("59 59 14 ? * MON-FRI"),
    NSE_BLOCK_DEAL_SECOND_SESSION_BETWEEN_02_05_TO_02_20_PM_MONDAY_TO_FRIDAY("0 05-20 14 ? * MON-FRI"),
    NSE_PRE_OPEN_MARKET_SESSION_BETWEEN_09_01_TO_09_09_AM_MONDAY_TO_FRIDAY("0 01-09 9 ? * MON-FRI"),

    NSE_PRE_OPEN_MAIL_BETWEEN_09_08_AM_TO_09_15_AM_MONDAY_TO_FRIDAY("0 14-08 9 ? * MON-FRI"),

    NSE_T_PLUS_0_LIVE_SESSION_BETWEEN_09_15_AM_TO_09_59_AM_MONDAY_TO_FRIDAY("0 15-59 09 ? * MON-FRI"),
    NSE_T_PLUS_0_LIVE_SESSION_BETWEEN_10_00_AM_TO_12_59_PM_MONDAY_TO_FRIDAY("0 * 10-12 ? * MON-FRI"),
    NSE_T_PLUS_0_LIVE_SESSION_BETWEEN_13_00_PM_TO_13_30_PM_MONDAY_TO_FRIDAY("0 0-30 13 ? * MON-FRI"),

    NSE_DAILY_TRADE_DETAILS_MAILER_MONDAY_TO_FRIDAY("0 08-20 09 ? * MON-FRI"),

    NSE_POST_MARKET_CLOSE_MONDAY_TO_FRIDAY_AT_05_00_PM("0 0 17 ? * MON-FRI"),
    NSE_POST_MARKET_CLOSE_MONDAY_TO_FRIDAY_AT_05_05_PM("0 5 17 ? * MON-FRI");


    private String cronExpression;

    private CronExpression(String cronExp){
        this.cronExpression = cronExp;
    }

    @Override
    public String toString() {
        return this.cronExpression;
    }
}
