package rave.code.quartz.enums;

public enum Group {

    TRADING_BATCH_1,
    TRADING_BATCH_2,
    INVESTING_BATCH_1,
    INVESTING_BATCH_2,
    MISCELLANEOUS_BATCH_1,
    MISCELLANEOUS_BATCH_2,
    HISTORY,
    STOCK_BASE,

    NSE_BLOCK_DEAL_SESSION,
    NSE_PRE_OPEN_MARKET_REGULAR_SESSION,
    NSE_PRE_OPEN_MARKET_SPECIAL_SESSION,
    NSE_LIVE_SESSION,
    NSE_POST_MARKET_CLOSE;

}
