package rave.code.quartz.enums;

public enum Group {

    TRADING_BATCH_1,
    TRADING_BATCH_2,
    INVESTING_BATCH_1,
    INVESTING_BATCH_2,
    MISCELLANEOUS_BATCH_1,
    MISCELLANEOUS_BATCH_2,
    HISTORY,
    STOCK_BASE,

    BLOCK_DEAL_SESSION,
    PRE_OPEN_REGULAR_SESSION,
    PRE_OPEN_SPECIAL_SESSION,
    POST_MARKET_CLOSE;

}
