package rave.code.quartz.enums;

public enum QuartzTrigger {

    BSE_ACTIVE_100_TRIGGER_NAME("BSEActive100Trigger"),
    BSE_ACTIVE_200_TRIGGER_NAME("BSEActive200Trigger"),
    BSE_ACTIVE_500_TRIGGER_NAME("BSEActive500Trigger"),
    BSE_PRICE_SHOCKERS_TRIGGER_NAME("BSEPriceShockersTrigger"),
    BSE_VOLUME_SHOCKERS_TRIGGER_NAME("BSEVolumeShockersTrigger"),

    BSE_TOP_DIVIDEND_TRIGGER_NAME("BSETopDividendTrigger"),
    BSE_MID_CAP_GAINER_TRIGGER_NAME("BSEMidCapGainerTrigger"),
    BSE_SMALL_CAP_GAINER_TRIGGER_NAME("BSESmallCapGainerTrigger"),

    BSE_SENSEX_TRIGGER_NAME("BSESensexTrigger"),
    BSE_STOCK_BASE_TRIGGER_NAME("BSEStockBaseTrigger"),

    BSE_ACTIVE_100_HISTORY_TRIGGER_NAME("BSEActive100HistoryTrigger"),
    BSE_ACTIVE_200_HISTORY_TRIGGER_NAME("BSEActive200HistoryTrigger"),
    BSE_ACTIVE_500_HISTORY_TRIGGER_NAME("BSEActive500HistoryTrigger"),
    BSE_PRICE_SHOCKER_HISTORY_TRIGGER_NAME("BSEPriceShockerHistoryTrigger"),
    BSE_VOLUME_SHOCKER_HISTORY_TRIGGER_NAME("BSEVolumeShockerHistoryTrigger"),

    NSE_POST_MARKET_CLOSE_TRIGGER("NSE Post Market CloseTrigger","T-POST-MARKET-CLOSE"),
    NSE_FIRST_BLOCK_DEAL_SESSION_TRIGGER("NSE Block Deal Session Trigger","T-FIRST-BLOCK-DEAL-SESSION"),
    NSE_SECOND_BLOCK_DEAL_SESSION_TRIGGER("NSE Block Deal Session Trigger","T-SECOND-BLOCK-DEAL-SESSION"),

    NSE_PRE_OPEN_MARKET_NIFTY_50_REGULAR_SESSION_TRIGGER("NSE Nifty-50 Pre Open Market Regular Session Trigger","T-NIFTY50-REG"),
    NSE_PRE_OPEN_MARKET_BANK_NIFTY_REGULAR_SESSION_TRIGGER("NSE Bank Nifty Pre Open Market Regular Session Trigger","T-BANK-NIFTY-REG"),
    NSE_PRE_OPEN_MARKET_SME_REGULAR_SESSION_TRIGGER("NSE SME Pre Open Market Regular Session Trigger","T-SME-REG"),
    NSE_PRE_OPEN_MARKET_FO_REGULAR_SESSION_TRIGGER("NSE FO Pre Open Market Regular Session Trigger","T-FO-REG"),
    NSE_PRE_OPEN_MARKET_OTHERS_REGULAR_SESSION_TRIGGER("NSE Others Pre Open Market Regular Session Trigger","T-OTHERS-REG"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_ETF_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-ETF-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_ETF_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-ETF-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_ETF_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-ETF-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_MAIN_BOARD_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-MB-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_MAIN_BOARD_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-MB-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_MAIN_BOARD_TRIGGER("NSE T+0 Slot-3 Live Session Trigger", "T-S3-MB-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_SME_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-SME-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_SME_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-SME-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_SME_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-SME-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_PRICE_SPURT_GTR_20_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-PS-SP>20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_PRICE_SPURT_GTR_20_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-PS-SP>20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_PRICE_SPURT_GTR_20_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-PS-SP>20-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_PRICE_SPURT_LWR_20_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-PS-SP<20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_PRICE_SPURT_LWR_20_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-PS-SP<20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_PRICE_SPURT_LWR_20_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-PS-SP<20-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_VOLUME_SPURT_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-VS-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_VOLUME_SPURT_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-VS-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_VOLUME_SPURT_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-VS-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_BANK_NIFTY_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-BN-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_BANK_NIFTY_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-T20-BN-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_BANK_NIFTY_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-T20-BN-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_FO_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-FO-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_FO_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-T20-FO-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_FO_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-T20-FO-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_NIFTY_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-N50-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_NIFTY_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-T20-N50-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_NIFTY_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-T20-N50-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_NIFTY_NEXT_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-NN50-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_NIFTY_NEXT_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-T20-NN50-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_NIFTY_NEXT_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-T20-NN50-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_SECURITY_GTR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-SP>20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_SECURITY_GTR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-T20-SP>20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_SECURITY_GTR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-T20-SP>20-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_SECURITY_LWR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-SP>20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_SECURITY_LWR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-T20-SP>20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_SECURITY_LWR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-T20-SP>20-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_BANK_NIFTY_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-BN-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_BANK_NIFTY_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-T20-BN-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_BANK_NIFTY_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-T20-BN-L-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_FO_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-FO-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_FO_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-T20-FO-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_FO_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-T20-FO-L-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_NIFTY_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-N50-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_NIFTY_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-T20-N50-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_NIFTY_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-T20-N50-L-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_NIFTY_NEXT_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-NN50-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_NIFTY_NEXT_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S1-T20-NN50-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_NIFTY_NEXT_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S1-T20-NN50-L-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_SECURITY_GTR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-SP>20-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_SECURITY_GTR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-T20-SP>20-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_SECURITY_GTR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-T20-SP>20-L-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_SECURITY_LWR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-S1-T20-SP<20-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_SECURITY_LWR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-S2-T20-SP<20-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_SECURITY_LWR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-S3-T20-SP<20-L-T+0"),

    NSE_PRE_OPEN_SPECIAL_SESSION_TRIGGER("NSE Pre Market Special Session Trigger", "T-Pre Open Session");

    private String name;
    private String shortName;

    private QuartzTrigger(String name){
        this.name = name;
    }
    private QuartzTrigger(String name, String shortName){
        this.name = name;
        this.shortName = shortName;
    }

    public String getName() {
        return name;
    }

    public String getShortName() {
        return shortName;
    }

    public String get(){
        return this.getName();
    }
}
