package rave.code.quartz.enums;

public enum QuartzTrigger {

    BSE_ACTIVE_100_TRIGGER_NAME("BSEActive100Trigger"),
    BSE_ACTIVE_200_TRIGGER_NAME("BSEActive200Trigger"),
    BSE_ACTIVE_500_TRIGGER_NAME("BSEActive500Trigger"),
    BSE_PRICE_SHOCKERS_TRIGGER_NAME("BSEPriceShockersTrigger"),
    BSE_VOLUME_SHOCKERS_TRIGGER_NAME("BSEVolumeShockersTrigger"),

    BSE_TOP_DIVIDEND_TRIGGER_NAME("BSETopDividendTrigger"),
    BSE_MID_CAP_GAINER_TRIGGER_NAME("BSEMidCapGainerTrigger"),
    BSE_SMALL_CAP_GAINER_TRIGGER_NAME("BSESmallCapGainerTrigger"),

    BSE_SENSEX_TRIGGER_NAME("BSESensexTrigger"),
    BSE_STOCK_BASE_TRIGGER_NAME("BSEStockBaseTrigger"),

    BSE_ACTIVE_100_HISTORY_TRIGGER_NAME("BSEActive100HistoryTrigger"),
    BSE_ACTIVE_200_HISTORY_TRIGGER_NAME("BSEActive200HistoryTrigger"),
    BSE_ACTIVE_500_HISTORY_TRIGGER_NAME("BSEActive500HistoryTrigger"),
    BSE_PRICE_SHOCKER_HISTORY_TRIGGER_NAME("BSEPriceShockerHistoryTrigger"),
    BSE_VOLUME_SHOCKER_HISTORY_TRIGGER_NAME("BSEVolumeShockerHistoryTrigger"),

    NSE_DAILY_TRADE_DETAILS_MAILER("NSE Daily Trade Details Trigger","T-DAILY-TRADE-DETAILS-MAILER(At 09:12)"),

    NSE_POST_MARKET_CLOSE_BHAVCOPY_TRIGGER("NSE Post Market Close Bhavcopy Trigger","T-POST-MARKET-CLOSE-BHAVCOPY(At 17:00)"),
    NSE_POST_MARKET_CLOSE_PE_RATIO_TRIGGER("NSE Post Market Close PE Ratio Trigger","T-POST-MARKET-CLOSE-PE-RATIO"),
    NSE_POST_MARKET_CLOSE_XXX_MOVING_AVERAGE_TRIGGER("NSE Post Market Close XXX Moving Average Trigger","T-POST-MARKET-CLOSE-XXX-MOVING-AVERAGE(At 17:05)"),

    NSE_FIRST_BLOCK_DEAL_SESSION_TRIGGER("NSE Block Deal Session Trigger","T-FIRST-BLOCK-DEAL-SESSION"),
    NSE_SECOND_BLOCK_DEAL_SESSION_TRIGGER("NSE Block Deal Session Trigger","T-SECOND-BLOCK-DEAL-SESSION"),

    NSE_PRE_OPEN_MARKET_REGULAR_SESSION_NIFTY_50_TRIGGER("NSE Nifty-50 Pre Open Market Trigger","T-PRE-OPEN-MARKET-REGULAR-SESSION-NIFTY50(09:01 - 09:09)"),
    NSE_PRE_OPEN_MARKET_REGULAR_SESSION_BANK_NIFTY_TRIGGER("NSE Bank Nifty Pre Open Market Trigger","T-PRE-OPEN-MARKET-REGULAR-SESSION-BANK-NIFTY(09:01 - 09:09)"),
    NSE_PRE_OPEN_MARKET_REGULAR_SESSION_SME_TRIGGER("NSE SME Pre Open Market Trigger","T-PRE-OPEN-MARKET-REGULAR-SESSION-SME(09:01 - 09:09)"),
    NSE_PRE_OPEN_MARKET_REGULAR_SESSION_FO_TRIGGER("NSE FO Pre Open Market Trigger","T-PRE-OPEN-MARKET-REGULAR-SESSION-FO(09:01 - 09:09)"),
    NSE_PRE_OPEN_MARKET_REGULAR_SESSION_OTHERS_TRIGGER("NSE Others Pre Open Market Trigger","T-PRE-OPEN-MARKET-REGULAR-SESSION-OTHERS(09:01 - 09:09)"),

    NSE_PRE_OPEN_MARKET_HISTORY_TRIGGER("NSE Pre Open Market History Trigger","T-PRE-OPEN-MARKET-HISTORY(At 09:10)"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_ETF_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-ETF-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_ETF_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-ETF-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_ETF_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-ETF-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_MAIN_BOARD_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-MB-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_MAIN_BOARD_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-MB-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_MAIN_BOARD_TRIGGER("NSE T+0 Slot-3 Live Session Trigger", "T-SLOT-3-MB-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_SME_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-SME-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_SME_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-SME-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_SME_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-SME-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_PRICE_SPURT_GTR_20_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-PRICE-SPURTS-STOCK-PRICE>20-T+0(09:15 - 09:59)"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_PRICE_SPURT_GTR_20_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-PRICE-SPURTS-STOCK-PRICE>20-T+0(10:00 - 12:59)"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_PRICE_SPURT_GTR_20_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-PRICE-SPURTS-STOCK-PRICE>20-T+0(13:00 - 13:30)"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_PRICE_SPURT_LWR_20_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-PRICE-SPURTS-STOCK-PRICE<20-T+0(09:15 - 09:59)"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_PRICE_SPURT_LWR_20_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-PRICE-SPURTS-STOCK-PRICE<20-T+0(10:00 - 12:59)"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_PRICE_SPURT_LWR_20_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-PRICE-SPURTS-STOCK-PRICE<20-T+0(13:00 - 13:30)"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_VOLUME_SPURT_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-VOLUME-SPURTS-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_VOLUME_SPURT_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-VOLUME-SPURTS-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_VOLUME_SPURT_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-VOLUME-SPURTS-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_BANK_NIFTY_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-BN-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_BANK_NIFTY_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-T20-BN-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_BANK_NIFTY_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-T20-BN-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_FO_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-FO-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_FO_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-T20-FO-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_FO_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-T20-FO-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_NIFTY_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-N50-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_NIFTY_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-T20-N50-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_NIFTY_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-T20-N50-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_NIFTY_NEXT_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-NN50-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_NIFTY_NEXT_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-T20-NN50-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_NIFTY_NEXT_50_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-T20-NN50-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_SECURITY_GTR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-SP>20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_SECURITY_GTR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-T20-SP>20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_SECURITY_GTR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-T20-SP>20-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_SECURITY_LWR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-SP>20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_SECURITY_LWR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-T20-SP>20-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_SECURITY_LWR_20_TOP_20_GAINER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-T20-SP>20-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_BANK_NIFTY_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-BN-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_BANK_NIFTY_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-T20-BN-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_BANK_NIFTY_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-T20-BN-L-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_FO_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-FO-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_FO_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-T20-FO-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_FO_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-T20-FO-L-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_NIFTY_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-N50-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_NIFTY_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-T20-N50-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_NIFTY_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-T20-N50-L-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_NIFTY_NEXT_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-NN50-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_NIFTY_NEXT_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-1-T20-NN50-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_NIFTY_NEXT_50_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-1-T20-NN50-L-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_SECURITY_GTR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-SP>20-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_SECURITY_GTR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-T20-SP>20-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_SECURITY_GTR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-T20-SP>20-L-T+0"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_SECURITY_LWR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-1 Live Session Trigger","T-SLOT-1-T20-SP<20-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_SECURITY_LWR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-2 Live Session Trigger","T-SLOT-2-T20-SP<20-L-T+0"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_SECURITY_LWR_20_TOP_20_LOSER_TRIGGER("NSE T+0 Slot-3 Live Session Trigger","T-SLOT-3-T20-SP<20-L-T+0"),

    NSE_PRE_OPEN_SPECIAL_SESSION_TRIGGER("NSE Pre Market Special Session Trigger", "T-PRE-OPEN-SPECIAL-SESSION");

    private String name;
    private String shortName;

    private QuartzTrigger(String name){
        this.name = name;
    }
    private QuartzTrigger(String name, String shortName){
        this.name = name;
        this.shortName = shortName;
    }

    public String getName() {
        return name;
    }

    public String getShortName() {
        return shortName;
    }

    public String get(){
        return this.getName();
    }
}
