package rave.code.quartz.enums;

public enum TriggerName {

    BSE_ACTIVE_100_TRIGGER_NAME("BSEActive100Trigger"),
    BSE_ACTIVE_200_TRIGGER_NAME("BSEActive200Trigger"),
    BSE_ACTIVE_500_TRIGGER_NAME("BSEActive500Trigger"),
    BSE_PRICE_SHOCKERS_TRIGGER_NAME("BSEPriceShockersTrigger"),
    BSE_VOLUME_SHOCKERS_TRIGGER_NAME("BSEVolumeShockersTrigger"),

    BSE_TOP_DIVIDEND_TRIGGER_NAME("BSETopDividendTrigger"),
    BSE_MID_CAP_GAINER_TRIGGER_NAME("BSEMidCapGainerTrigger"),
    BSE_SMALL_CAP_GAINER_TRIGGER_NAME("BSESmallCapGainerTrigger"),

    BSE_SENSEX_TRIGGER_NAME("BSESensexTrigger"),
    BSE_STOCK_BASE_TRIGGER_NAME("BSEStockBaseTrigger"),

    BSE_ACTIVE_100_HISTORY_TRIGGER_NAME("BSEActive100HistoryTrigger"),
    BSE_ACTIVE_200_HISTORY_TRIGGER_NAME("BSEActive200HistoryTrigger"),
    BSE_ACTIVE_500_HISTORY_TRIGGER_NAME("BSEActive500HistoryTrigger"),
    BSE_PRICE_SHOCKER_HISTORY_TRIGGER_NAME("BSEPriceShockerHistoryTrigger"),
    BSE_VOLUME_SHOCKER_HISTORY_TRIGGER_NAME("BSEVolumeShockerHistoryTrigger"),

    NSE_POST_MARKET_CLOSE_TRIGGER("NSE Post Market CloseTrigger"),
    NSE_FIRST_BLOCK_DEAL_SESSION_TRIGGER("NSE Block Deal Session Trigger"),

    NSE_PRE_OPEN_MARKET_NIFTY_50_REGULAR_SESSION_TRIGGER("NSE Nifty-50 Pre Open Market Regular Session Trigger"),
    NSE_PRE_OPEN_MARKET_BANK_NIFTY_REGULAR_SESSION_TRIGGER("NSE Bank Nifty Pre Open Market Regular Session Trigger"),
    NSE_PRE_OPEN_MARKET_SME_REGULAR_SESSION_TRIGGER("NSE SME Pre Open Market Regular Session Trigger"),
    NSE_PRE_OPEN_MARKET_FO_REGULAR_SESSION_TRIGGER("NSE FO Pre Open Market Regular Session Trigger"),
    NSE_PRE_OPEN_MARKET_OTHERS_REGULAR_SESSION_TRIGGER("NSE Others Pre Open Market Regular Session Trigger"),

    NSE_T_PLUS_0_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),

    NSE_T_PLUS_0_ETF_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_ETF_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_ETF_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_MAIN_BOARD_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_MAIN_BOARD_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_MAIN_BOARD_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_SME_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_SME_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_SME_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_PRICE_SPURT_GTR_20_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_PRICE_SPURT_GTR_20_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_PRICE_SPURT_GTR_20_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_PRICE_SPURT_LWR_20_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_PRICE_SPURT_LWR_20_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_PRICE_SPURT_LWR_20_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_VOLUME_SPURT_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_VOLUME_SPURT_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_VOLUME_SPURT_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),

    NSE_T_PLUS_0_BANK_NIFTY_TOP_20_GAINER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_BANK_NIFTY_TOP_20_GAINER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_BANK_NIFTY_TOP_20_GAINER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_FO_TOP_20_GAINER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_FO_TOP_20_GAINER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_FO_TOP_20_GAINER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_50_TOP_20_GAINER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_50_TOP_20_GAINER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_50_TOP_20_GAINER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_NEXT_50_TOP_20_GAINER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_NEXT_50_TOP_20_GAINER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_NEXT_50_TOP_20_GAINER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_GTR_20_TOP_20_GAINER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_GTR_20_TOP_20_GAINER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_GTR_20_TOP_20_GAINER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_LWR_20_TOP_20_GAINER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_LWR_20_TOP_20_GAINER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_LWR_20_TOP_20_GAINER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),

    NSE_T_PLUS_0_BANK_NIFTY_TOP_20_LOSER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_BANK_NIFTY_TOP_20_LOSER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_BANK_NIFTY_TOP_20_LOSER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_FO_TOP_20_LOSER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_FO_TOP_20_LOSER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_FO_TOP_20_LOSER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_50_TOP_20_LOSER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_50_TOP_20_LOSER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_50_TOP_20_LOSER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_NEXT_50_TOP_20_LOSER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_NEXT_50_TOP_20_LOSER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_NIFTY_NEXT_50_TOP_20_LOSER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_GTR_20_TOP_20_LOSER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_GTR_20_TOP_20_LOSER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_GTR_20_TOP_20_LOSER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_LWR_20_TOP_20_LOSER_LIVE_SESSION_SLOT_1_TRIGGER("NSE T+0 Slot-1 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_LWR_20_TOP_20_LOSER_LIVE_SESSION_SLOT_2_TRIGGER("NSE T+0 Slot-2 Live Session Trigger"),
    NSE_T_PLUS_0_SECURITY_LWR_20_TOP_20_LOSER_LIVE_SESSION_SLOT_3_TRIGGER("NSE T+0 Slot-3 Live Session Trigger"),

    NSE_PRE_OPEN_SPECIAL_SESSION_TRIGGER("NSE Pre Market Special Session Trigger");

    private String name;

    private TriggerName(String name){
        this.name = name;
    }

    public String get(){
        return this.name;
    }
}
