#------------------------------#
# HikariCP specific properties #
#------------------------------#
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000