USE stock_market;

DELETE FROM QUARTZ_SIMPLE_TRIGGERS WHERE TRIGGER_NAME LIKE 'TEST%';
DELETE FROM QUARTZ_BLOB_TRIGGERS WHERE TRIGGER_NAME LIKE 'TEST%';
DELETE FROM QUARTZ_CRON_TRIGGERS WHERE TRIGGER_NAME LIKE 'TEST%';
DELETE FROM QUARTZ_SIMPROP_TRIGGERS WHERE TRIGGER_NAME LIKE 'TEST%';
DELETE FROM QUARTZ_TRIGGERS WHERE JOB_NAME LIKE 'TEST%';
DELETE FROM QUARTZ_JOB_DETAILS WHERE JOB_NAME LIKE 'TEST%';

DELETE FROM nse_pre_open_market_detail WHERE symbol LIKE 'TEST%';
DELETE FROM nse_price_to_earning_ratio_detail WHERE symbol LIKE 'TEST%';
DELETE FROM nse_stock_base WHERE symbol LIKE 'TEST-%';

COMMIT;