<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.5</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <name>nse-india-springboot-webapp</name>
    <groupId>rave.code.java.stock-market.sm-web-systems</groupId>
    <artifactId>nse-india-springboot-webapp</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>war</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>17</maven.compiler.release>
        <java.version>17</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-logging</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!--
            Below dependency is included for the sake of hot deployment...including this module alone would not enable
            hot deployment feature of spring boot...some tweaks need to be done at the IDE level too... in my case i was using
            IntelliJ. the following steps would let you enable the hot deployment feature of spring boot and enables easy
            development...

            1. adding the devtools dependency to the project
            2. In Intellij goto
                File->Settings-> Build-Execution-Deployment -> Compiler
            3. Build project automatically option...by default it will be unchecked
            4. In older version of intelliJ instead of "Build project automatically" you would be having "Make project automatically"
            5. Restart the IDE...i,e IntelliJ
        -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
        </dependency>

        <!-- Thymeleaf dependencies -->
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf</artifactId>
            <version>3.1.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf-spring6</artifactId>
            <version>3.1.2.RELEASE</version>
        </dependency>

        <!-- Module dependencies  -->
        <dependency>
            <groupId>rave.code.java.stock-market.sm-sub-systems</groupId>
            <artifactId>sm-repository-system</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>rave.code.java.stock-market.sm-sub-systems</groupId>
            <artifactId>sm-data-parser-system</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>rave.code.java.stock-market.sm-sub-systems</groupId>
            <artifactId>sm-quartz-scheduler-system</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>rave.code.java.stock-market.sm-sub-systems</groupId>
            <artifactId>sm-utility-system</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>rave.code.java.utilities.log-decors</groupId>
            <artifactId>java-util-log-decor</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <!--<include>**/*</include>-->
                    <include>**/logback-spring.xml</include>
                    <include>**/quartz-override.properties</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <!--<plugin>
                <groupId>rave.code.java.stock-market</groupId>
                <artifactId>sm-maven-plugin</artifactId>
                <version>1.0.0-SNAPSHOT</version>
                <configuration>
                    <dbServerUrl>jdbc:mysql://localhost:3306/</dbServerUrl>
                    <driver>com.mysql.cj.jdbc.Driver</driver>
                    <databaseName>stock_market</databaseName>
                    <username>admin</username>
                    <password>admin</password>
                </configuration>
                <dependencies>
                    &lt;!&ndash; https://mvnrepository.com/artifact/mysql/mysql-connector-java &ndash;&gt;
                    <dependency>
                        <groupId>com.mysql</groupId>
                        <artifactId>mysql-connector-j</artifactId>
                        <version>8.0.33</version>
                    </dependency>
                </dependencies>
            </plugin>-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>del-dev-and-prod</id>
                        <!-- runs before jar is packaged -->
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <echo message="Deleting target/classes/dev and target/classes/prod before packaging..."/>
                                <delete dir="${project.build.directory}/classes/dev"/>
                                <delete dir="${project.build.directory}/classes/prod"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources/dev</directory>
                        <filtering>false</filtering>
                    </resource>
                    <resource>
                        <directory>src/main/resources</directory>
                        <filtering>false</filtering>
                    </resource>
                </resources>
                <plugins>
                    <plugin>
                        <groupId>rave.code.java.stock-market</groupId>
                        <artifactId>sm-maven-plugin</artifactId>
                        <version>1.0.0-SNAPSHOT</version>
                        <configuration>
                            <dbServerUrl>jdbc:mysql://localhost:3306/</dbServerUrl>
                            <driver>com.mysql.cj.jdbc.Driver</driver>
                            <databaseName>stock_market_dev</databaseName>
                            <username>admin</username>
                            <password>admin</password>
                        </configuration>
                        <dependencies>
                            <!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java -->
                            <dependency>
                                <groupId>com.mysql</groupId>
                                <artifactId>mysql-connector-j</artifactId>
                                <version>8.0.33</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>prod</id>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources/prod</directory>
                        <filtering>false</filtering>
                    </resource>
                    <resource>
                        <directory>src/main/resources</directory>
                        <filtering>false</filtering>
                    </resource>
                </resources>
                <plugins>
                    <plugin>
                        <groupId>rave.code.java.stock-market</groupId>
                        <artifactId>sm-maven-plugin</artifactId>
                        <version>1.0.0-SNAPSHOT</version>
                        <configuration>
                            <dbServerUrl>jdbc:mysql://localhost:3306/</dbServerUrl>
                            <driver>com.mysql.cj.jdbc.Driver</driver>
                            <databaseName>stock_market</databaseName>
                            <username>admin</username>
                            <password>admin</password>
                        </configuration>
                        <dependencies>
                            <!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java -->
                            <dependency>
                                <groupId>com.mysql</groupId>
                                <artifactId>mysql-connector-j</artifactId>
                                <version>8.0.33</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
